import pandas as pd
import numpy as np


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Calculates returns, annualized volatility, and momentum."""
    print("Engineering time-series features...")
    data = df.copy()

    # Daily Returns
    data['Return'] = data['Close'].pct_change()

    # Annualized Rolling Volatility (21 trading days)
    data['Volatility_21d'] = data['Return'].rolling(
        window=21).std() * np.sqrt(252)

    # Rolling Momentum (21 days)
    data['Momentum_21d'] = data['Close'] / data['Close'].shift(21) - 1

    # Drop NaN values generated by rolling windows
    return data.dropna()
